#!/bin/bash
# Setup Script untuk Portfolio Melky Raham Ariyanto

echo "=========================================="
echo "Portfolio Melky Raham Ariyanto"
echo "Junior Programmer | Certified BNSP"
echo "=========================================="
echo ""
echo "✅ Struktur folder sudah dibuat:"
echo ""
echo "portofolio melky/"
echo "├── index.html              ← Halaman Home"
echo "├── cv.html                 ← Halaman CV"
echo "├── portfolio.html          ← Halaman Portfolio"
echo "├── surat-lamaran.html      ← Halaman Surat Lamaran"
echo "├── QUICK_START.html        ← Panduan Setup (buka di browser)"
echo "├── README.md               ← Dokumentasi lengkap"
echo "│"
echo "├── css/"
echo "│   ├── style.css           ← CSS Global"
echo "│   ├── cv.css              ← Styling CV"
echo "│   ├── portfolio.css       ← Styling Portfolio"
echo "│   └── surat-lamaran.css   ← Styling Surat Lamaran"
echo "│"
echo "├── js/"
echo "│   ├── script.js           ← JavaScript Global"
echo "│   ├── portfolio.js        ← Fitur Filter Portfolio"
echo "│   └── surat-lamaran.js    ← Fitur Form & Surat"
echo "│"
echo "└── assets/                 ← Folder untuk images (opsional)"
echo ""
echo "=========================================="
echo "🚀 QUICK START"
echo "=========================================="
echo ""
echo "1. Buka file QUICK_START.html di browser untuk panduan interaktif"
echo "   atau"
echo ""
echo "2. Gunakan Live Server di VS Code:"
echo "   - Klik kanan di index.html"
echo "   - Pilih 'Open with Live Server'"
echo ""
echo "3. Buka browser ke http://localhost:5500"
echo ""
echo "=========================================="
echo "📝 FILES TO EDIT"
echo "=========================================="
echo ""
echo "Edit file ini untuk customize portfolio Anda:"
echo ""
echo "• cv.html              → Update email, nomor, pengalaman kerja"
echo "• portfolio.html       → Tambah/edit proyek Anda"
echo "• surat-lamaran.html   → Customize isi surat lamaran"
echo "• index.html           → Update info kontak"
echo ""
echo "=========================================="
echo "💡 TIPS"
echo "=========================================="
echo ""
echo "✓ Semua file HTML, CSS, JS sudah siap digunakan"
echo "✓ Design responsive untuk mobile, tablet, desktop"
echo "✓ Portfolio ini ready to deploy ke GitHub Pages"
echo "✓ Customize data pribadi sebelum dishare ke recruiter"
echo ""
echo "=========================================="
echo "📧 CONTACT INFO TO UPDATE"
echo "=========================================="
echo ""
echo "Di semua file HTML, update:"
echo ""
echo "❌ melky.ariyanto@email.com    → Email Anda"
echo "❌ +62 812-3456-7890          → Nomor WhatsApp Anda"
echo "❌ linkedin.com/in/melky       → LinkedIn profile Anda"
echo "❌ github.com/melky            → GitHub profile Anda"
echo ""
echo "=========================================="
echo ""
echo "✨ Portfolio Anda sudah siap! Happy coding! 🚀"
echo ""
